---
- name: "Install Applications"
  hosts: "all"

  tasks:

  - name: "/!/ Utility packages"
    package:
      name:
        - rsync
        - pv
        - patch
        - zip
        - unzip
        - fzf
        - ripgrep
        - ripgrep-all
        - btop
        - cmus
        - evince
        - pandoc-cli
        - transmission-gtk
    become: true

  - name: "/!/ Dev packages"
    package:
      name:
        - base-devel
    become: true

  # TODO: Check if it is needed.
  - name: "/!/ brightnessctl"
    package:
      name: brightnessctl
    become: true

  # TODO: Add to GUI packages.
  - name: "/!/ Image packages"
    package:
      name:
        - gimp
        - eog
    become: true

  # TODO: Check if GUI installed.
  - name: "/!/ GUI packages"
    package:
      name:
        - fontforge
    become: true

- import_playbook: "{{ playbook_dir }}/app/mpv.yml"
- import_playbook: "{{ playbook_dir }}/app/tmux.yml"
- import_playbook: "{{ playbook_dir }}/app/vim.yml"
