---
- name: "Hyprland config"
  hosts: "all"

  vars:

    config:
      name: "hyprland.conf"
      dir: "{{ XDG_CONFIG_HOME }}"

  tasks:

  - import_tasks: "{{ playbook_dir }}/wayland/app.yml"

  - name: "/!/ Hyprland"
    package:
      name: "hyprland"
    become: true

  - name: "/!/ {{ config.name }}"
    copy:
      src: "{{ uws }}/config/{{ config.name }}"
      dest: "{{ config.dir }}/hypr/{{ config.name }}"
