---
- name: Hyprland config
  hosts: all

  vars:

    # Quoted to prevent adding the EOL.
    config_dir: "{{ ansible_env.XDG_CONFIG_HOME
        | default( (ansible_env.HOME, '.config') | path_join )
      }}"

    config_name: hyprland.conf
    config_path: "{{ (config_dir, 'hypr', config_name) | path_join }}"

  tasks:

  - name: ⚠ XDG_CONFIG_HOME
    when: ansible_env.XDG_CONFIG_HOME | default('') == ''
    debug:
      msg: "$XDG_CONFIG_HOME is not set, using the default '{{ config_dir }}'."

  - name: ∎ hyprland.conf
    file:
      path: "{{ config_path }}"
      src: "{{ ( uws, 'config', config_name ) | path_join }}"
      state: link
      force: true
