---
- name: Hyprland config
  hosts: all

  vars:

    config:
      name: hyprland.conf
      dir: >-
        {{
          ansible_env.XDG_CONFIG_HOME
          | default((ansible_env.HOME, '.config') | path_join)
        }}

  tasks:

  - import_tasks: "{{ playbook_dir }}/wayland/app.yml"

  - name: /!/ Hyprland
    package:
      name: hyprland
    become: true

  - name: /!/ XDG_CONFIG_HOME
    when: ansible_env.XDG_CONFIG_HOME | default('') == ''
    debug:
      msg: > 
        [WARN] $XDG_CONFIG_HOME is not set,
        using the default '{{ config.dir }}'.

  - name: "/!/ '{{ config.name }}'"
    file:
      path: "{{ config.dir }}/hypr/{{ config.name }}"
      src: "{{ uws }}/config/{{ config.name }}"
      state: link
      force: true
