#!/bin/bash

uws="${uws:-$(cd $(dirname $BASH_SOURCE[0]) && pwd)}"

ansible-playbook \
  --inventory=localhost, \
  --connection=local \
  --ask-become-pass \
  --extra-vars="uws='$uws' app='$(xdg-user-dir APP)'" \
  $uws/playbook/$1.yml
