#!/bin/bash


usage() {
cat << EOF
Configure Unix with Ansible:

  uws set [target] {<user>@<host>:<port> {--private-key=<path>}}

  The [target] can be:
    * <playbook>
    * roles/<role>
    * roles/<namespace>.<collection>.<role>
    * tasks/<relative path within a role>

  If the optional second arg is passed, it will be used as the target remote
  host to connect to via SSH using a password or '--private-key'.

Local Ansible docs:

    uws doc

Run tests:

  uws test {sh|py|ansible}

Local Ansible playbooks and roles are located in 'lib/ansible_collections'.
EOF
}


uws="$(cd $(dirname $BASH_SOURCE[0]) && pwd)"
exe="$uws/util/uws/${1:-}.sh"

[[ ! -f "$exe" ]] && {
  usage
  exit 1
}

shift
"$exe" $@
