#!/bin/bash


usage() {
cat << EOF
Configure Linux with Ansible:

  uws set [target] {<user>@<host>:<port> {--private-key=<path>}}

  The required [target] arg can be:
    * <playbook>
    * roles/<role>
    * roles/<namespace>.<collection>.<role>
    * tasks/<relative path within a role>

  If the optional second arg is passed, runs via SSH. If no '--private-key' is
  provided as the third arg, uses the password for auth.

Run tests:

  uws test {sh|py|ansible}

Local Ansible docs:
  List plugins:
    uws doc -l
    uws doc -l local.uws
  Show a local <plugin> doc:
    uws doc local.uws.<plugin>

Ansible playbooks and roles are located in 'lib/ansible_collections'.
EOF
}


uws="$(cd $(dirname $BASH_SOURCE[0]) && pwd)"
exe="$uws/util/uws/${1:-}.sh"

[[ ! -f "$exe" ]] && {
  usage
  exit 1
}

shift
"$exe" $@
