#!/bin/bash

uws=$(cd $(dirname $BASH_SOURCE[0]) && pwd)

. "$uws/lib/python.sh"


usage() {
cat << EOF
Usage:
  uws set
  uws set <playbook>

The <playbook> is a base file name.
EOF
}


check_args() {

  [[ $1 != "set" ]] \
    && usage \
    && return 1

  return 0
}


check_args ${1:-} ${2:-} || exit 1

[[ $1 == "set" ]] \
  && exe=ansible

[[ $1 == "set" ]] \
  && option=${2:-main}

# TODO: check that Ansible already evailable.
ensure_venv "$uws/venv" || exit 2

"$uws/$exe" $option
