---
- name: "Media"
  hosts: "all"

  tasks:

  # TODO: Check if GUI installed.
  - name: "/!/ Media packages"
    package:
      name:
        - mpv
        - yt-dlp
    become: true

  # Use `dla <URL>` to download MP3.
  - name: "Aliases for YouTube downloading"
    local.uws.config_option:
      file: "{{ ansible_env.HOME }}/.bashrc.auto"
      option: "alias dla"
      value: "'yt-dlp --extract-audio --audio-format mp3 --audio-quality 0'"

