---
- name: "Media"
  hosts: "all"

  tasks:

  # TODO: Check if GUI installed.
  - name: "/!/ Media packages"
    package:
      name:
        - mpv
        - yt-dlp
    become: true

  # Use `dla <URL>` to download mp3.
  # TODO: Ensure exacly one unique line.
  - name: "Aliases for YouTube downloading"
    lineinfile:
      path: "{{ ansible_env.HOME }}/.bashrc.auto"
      line: >
        alias dla='yt-dlp --extract-audio --audio-format mp3 --audio-quality 0'
