---
- name: "Vim setup"
  hosts: "all"

  vars:
    dotvim_link: "{{ (ansible_env.HOME, '.vim') | path_join }}"
    dotvimrc_link: "{{ (ansible_env.HOME, '.vimrc') | path_join }}"

  tasks:

  - name: "/!/ Vim package"
    package:
      name: "vim"
    become: true

  - name: "/?/ .vim symlink"
    stat:
      path: "{{ dotvim_link }}"
    register: dotvim_file

  - name: "Delete dir '{{ dotvim_link }}'"
    when: not dotvim_file.stat.islnk
    file:
      path: "{{ dotvim_link }}"
      state: "absent"

  - name: "/!/ {{ dotvim_link }}"
    file:
      path: "{{ dotvim_link }}"
      src: "{{ (uws, 'res', 'vim') | path_join }}"
      state: "link"
      force: true

  - name: "/!/ {{ dotvimrc_link }}"
    file:
      path: "{{ dotvimrc_link }}"
      src: "{{ (uws, 'config', 'vimrc') | path_join }}"
      state: "link"
      force: true
