#!/bin/bash

# Download the Input font zip to the `destination_dir`.

notification_title="[Input]"

# Includes {{{
lib="$(cd "$(dirname "$BASH_SOURCE[0]")/../../../lib" && pwd)"
. "$lib/notifications.sh" || exit 1
# Includes }}}

# Destination {{{
destination_dir="${1:-}"

[[ -z "$destination_dir" ]] && {
  ERR "Destination dir is not set!"
  exit 2
}

[[ -d "$destination_dir" ]] || {
  ERR "Destination dir does not exist!"
  exit 2
}
# Destination }}}

INFO "Download"

referer="https://input.djr.com/download/index.html?size=16&language=javascript"
referer="$referer&theme=monokai&family=InputMono&width=400&weight=400"
referer="$referer&line-height=1.3&a=ss&g=ss&i=topserif&l=serifs_round"
referer="$referer&zero=slash&asterisk=height&braces=straight&preset=sourcecode"
referer="$referer&customize=please"

user_agent="Mozilla/5.0 (X11; Linux x86_64; rv:132.0)"
user_agent="$user_agent Gecko/20100101 Firefox/132.0"
accept="text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"

# These cookies are ignored:
#   --cookie "_ga=GA<...>" \
#   --cookie "_gid=GA<...>" \
#   --cookie "_ga_Z5S6C1FSZH=GS<...>" \
#   --cookie "_gat=1" \
curl \
  --location \
  --header "Referer: $referer" \
  --header "User-Agent: $user_agent" \
  --header "Accept: $accept" \
  --header "Accept-Encoding: gzip, deflate, br, zstd" \
  --header "Accept-Language: en-US,en;q=0.5" \
  --header "Connection: keep-alive" \
  --header "Upgrade-Insecure-Requests: 1" \
  --header "Sec-Fetch-Dest: document" \
  --header "Sec-Fetch-Mode: navigate" \
  --header "Sec-Fetch-Site: same-origin" \
  --header "Sec-Fetch-User: ?1" \
  --header "Priority: u=0, i" \
  --header "TE: trailers" \
  --request GET \
    --get \
      --data "fontSelection=fourStyleFamily" \
      --data "regular=InputMono-Regular" \
      --data "italic=InputMono-Italic" \
      --data "bold=InputMono-Bold" \
      --data "boldItalic=InputMono-BoldItalic" \
      --data "a=ss" \
      --data "g=ss" \
      --data "i=topserif" \
      --data "l=serifs_round" \
      --data "zero=slash" \
      --data "asterisk=height" \
      --data "braces=straight" \
      --data "preset=sourcecode" \
      --data "line-height=1.3" \
      --data "accept=I%20do" \
      --data "email=" \
  --remote-name \
  --output-dir "$destination_dir" \
  "https://input.djr.com/build"
